name: 'Run Ruff Python Linter with reviewdog'
description: ' 🐶 Run Ruff Python Linter with reviewdog on pull requests to improve code review experience.'
author: 'Aaron (AJ) Steers'
inputs:
  github_token:
    description: 'GITHUB_TOKEN'
    default: '${{ github.token }}'
  workdir:
    description: 'Working directory relative to the root directory.'
    default: '.'
  ### Flags for reviewdog ###
  level:
    description: 'Report level for reviewdog [info,warning,error]'
    default: 'error'
  reporter:
    description: 'Reporter of reviewdog command [github-pr-check,github-pr-review].'
    default: 'github-pr-check'
  filter_mode:
    description: |
      Filtering mode for the reviewdog command [added,diff_context,file,nofilter].
      Default is added.
    default: 'added'
  fail_on_error:
    description: |
      Exit code for reviewdog when errors are found [true,false]
      Default is `false`.
    default: 'false'
  reviewdog_flags:
    description: 'Additional reviewdog flags'
    default: ''
  ### Flags for ruff ###
  ruff_command:
    description: 'Allows you to override the ruff entrypoint. For example, use `poetry run ruff` to use the version defined in your Poetry repo. Else, the ruff version used will be from `pip install ruff`.'
    default: 'ruff'
  target:
    description: 'Target directory to run ruff.'
    default: '.'
runs:
  using: 'docker'
  image: 'Dockerfile'

# Ref: https://haya14busa.github.io/github-action-brandings/
branding:
  icon: 'check'
  color: 'purple'
